# Generated by Django 3.2.9 on 2022-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_book_picture_alter_issue_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_renewed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Renewed'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date Returned'),
        ),
    ]
