# Generated by Django 4.0.3 on 2022-04-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitve_Examination',
        ),
        migrations.DeleteModel(
            name='Conferenceandpaperpresentation',
        ),
        migrations.DeleteModel(
            name='Project_Presentation',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
