# Generated by Django 4.0.3 on 2022-04-12 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0002_delete_competitve_examination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_agency', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('year_receipt', models.DateField()),
                ('proof', models.ImageField(upload_to='Scholarship')),
                ('userdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('agency_applied', models.CharField(max_length=30)),
                ('project_status', models.CharField(max_length=100)),
                ('outcome', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('grantamount', models.IntegerField()),
                ('fromdate', models.DateField(default=django.utils.timezone.now)),
                ('todate', models.DateField(default=django.utils.timezone.now)),
                ('proof', models.ImageField(upload_to='Project_Presentation')),
                ('userdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference_and_Paperpresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationtype', models.CharField(choices=[('PUBLISHED', 'Published'), ('PRESENTED', 'Presented'), ('OTHERS', 'Others')], max_length=200)),
                ('colloborativeevent', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=200)),
                ('colloboration', models.CharField(choices=[('SELF', 'Self'), ('STUDENTS', 'Students'), ('INDUSTRY', 'Industry'), ('INTERNAL', 'Internal Faculty Member'), ('EXTERNAL', 'External Faculty Member')], max_length=200)),
                ('authorname', models.CharField(max_length=200)),
                ('papername', models.CharField(max_length=200)),
                ('guidename', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International'), ('UGC', 'UGC'), ('OTHERS', 'Others')], max_length=200)),
                ('type', models.CharField(choices=[('JOURNAL', 'Journal'), ('CONFERENCE', 'Conference'), ('SYMPOSIUM', 'Symposium')], max_length=200)),
                ('conferencename', models.CharField(max_length=200)),
                ('organizedname', models.CharField(max_length=200)),
                ('fromdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('todate', models.DateTimeField(default=django.utils.timezone.now)),
                ('paidstatus', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=200)),
                ('indexing', models.CharField(choices=[('SCOPUS', 'Scopus'), ('WEB', 'Web of Science'), ('SCI', 'SCI'), ('SCIE', 'SCIE'), ('UGC', 'UGC'), ('NON-SCOPUS', 'Non-Scopus'), ('ANNEXURE', 'Annexure I')], max_length=200)),
                ('issnorisbnnumber', models.CharField(max_length=200)),
                ('impactfactor', models.CharField(max_length=200)),
                ('monthofpublication', models.DateTimeField(default=django.utils.timezone.now)),
                ('yearofpublication', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume', models.CharField(max_length=200)),
                ('issuenumber', models.CharField(max_length=200)),
                ('pagenumber', models.CharField(max_length=200)),
                ('proof', models.ImageField(upload_to='Conference_and_Paperpresentation')),
                ('userdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competitive_Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(choices=[('NET', 'NET'), ('SLET', 'SLET'), ('IIT', 'IIT'), ('GATE', 'GATE'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('CAT', 'CAT'), ('JAM', 'JAM'), ('IELET', 'IELET'), ('TOEFL', 'TOEFL'), ('CIVIL', 'Civil Services'), ('STATE', 'State Gov. Exam'), ('CENTRAL', 'Central Gov. Exam'), ('OTHERS', 'Others')], max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('marks', models.IntegerField()),
                ('qualified', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=100)),
                ('success_details', models.TextField(max_length=300)),
                ('proof', models.ImageField(upload_to='Competitive_Examination')),
                ('userdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
