# Generated by Django 4.0.4 on 2022-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_scholarship_project_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
