# Generated by Django 4.0.4 on 2022-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_cocurricular_and_extra_curricular_activities_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocurricular_and_extra_curricular_activities',
            old_name='achievements',
            new_name='achievement',
        ),
        migrations.AlterField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='Sponsoredorcolloboration',
            field=models.CharField(choices=[('INDUSTRY', 'Industry'), ('FOREIGN UNIVERSITY', 'Foreign University '), ('INTERNAL', 'Internal '), ('EXTERNAL', 'External'), ('NPTEL', 'NPTEL'), ('COURSERA', 'Coursera'), ('EDX', 'EDX'), ('UDEMY', 'Udemy'), ('OTHERS', 'Others')], max_length=30),
        ),
    ]
