# Generated by Django 4.0.4 on 2022-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_cocurricular_and_extra_curricular_activities_sponsoredorcolloboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='achievement',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Participation', 'Participation'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='amountsponsored',
            field=models.CharField(choices=[('External Agency', 'External Agency'), ('KCT', 'KCT'), ('Self', 'Self'), ('Not Applicable', 'Not Applicable')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='level',
            field=models.CharField(choices=[('Zonal', 'Zonal'), ('District', 'District'), ('State', 'State'), ('National', 'National'), ('International', 'International'), ('Reginol', 'Regional'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='conference_and_paperpresentation',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International'), ('UGC', 'UGC'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='conference_and_paperpresentation',
            name='colloboration',
            field=models.CharField(choices=[('Self', 'Self'), ('Students', 'Students'), ('Industry', 'Industry'), ('Internal', 'Internal Faculty Member'), ('External', 'External Faculty Member')], max_length=200),
        ),
        migrations.AlterField(
            model_name='conference_and_paperpresentation',
            name='publicationtype',
            field=models.CharField(choices=[('Published', 'Published'), ('Presented', 'Presented'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='conference_and_paperpresentation',
            name='type',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Symposium', 'Symposium')], max_length=200),
        ),
    ]
