# Generated by Django 4.0.4 on 2022-04-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_alter_cocurricular_and_extra_curricular_activities_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocurricular_and_extra_curricular_activities',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Guest Lecture', 'Guest Lecture'), ('Outreach Programme', 'Outreach Programme'), ('Certification Course', 'Certification Course '), ('Sports', 'Sports'), ('One Credit Course', 'One Credit Course'), ('NCC', 'NCC')], max_length=30),
        ),
    ]
